<a href="https://colab.research.google.com/github/hitesh-choudhary25/Gitam19/blob/master/Python(28_06_2019).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to Object Oriented Programming in Python**

One of the popular approach to solve the programming by creating an object.This Object Oriented Programming.

An object has two characteristics:

1. attributes(name,age,color)

2. behaviour(learn,study,singing,dance)

In pyhton,the concept  Object Oriented Programming follow this things:

1. Inheritance

2. Encapsulation

3.  Polymorphism

**Class**:-

A class is a blueprint of an object and it is also called as Logical entity.

**Object**:-

Blueprint of class or instance of the class or physical entity.

**Methods**:-

Part of class can be called with object.

**Constructor**:-

Part of class can be called automatically .

**Inheritance**:-





In [1]:
def test():
  print("test()for function")
  return
test()

test()for function


In [3]:
class Demo:
  def test(self):
    print("test() for the class and method")
    return
  
obj = Demo()
obj.test()

test() for the class and method


In [4]:
class Demo1:
  def fact(self,n):
    #return the factorial 
    fact = 1
    while(n!=0):
      fact = fact * n
      n = n - 1
    return fact
  
p1 = Demo1()
print(p1.fact(5))

120


In [5]:
class Demo2:
  def _init_(self,p1,p2):
    self.p1 = p1
    self.p2 = p2
    
  def add(self,p1,p2):
    return p1 + p2
  
c1 = Demo2()
print(c1.add(100,200))

300


In [10]:
class Demo3:
  def _init_(self,p1,p2):
    self.p1 = p1
    self.p2 = p2
    
  def sub(self,p1,p2):
    return p1 - p2
  
c1 = Demo3()
print(c1.sub(200,100))

100


In [9]:
class Demo4:
  def _init_(self,p1,p2):
    self.p1 = p1
    self.p2 = p2
    
  def mul(self,p1,p2):
    return p1 * p2
  
c1 = Demo4()
print(c1.mul(100,200))

20000


In [19]:
#some inheritance
#parent class
class Person(object):
  #constructor
  def __init__(self,name):
    self.name = name
  def getName(self):
    return self.name
  def isEmployee(self):
    return False
  
#Derived class
class Employee(Person):
  def isEmployee(self):
    return True

emp = Person("Anil")
print(emp.getName(),emp.isEmployee())

emp1 = Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

Anil False
Akhil True


**Python Numpy**

Numpy arrays is a bit like python list




In [20]:
import numpy as np
lst = [1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [21]:
lst = [1,2,3,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [22]:
lst = [1,0,4,5,6.2,8,3]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(7,)
float64


In [44]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [27]:
#Re-shape the given array
#numpy.reshape(arrayName,reshape,order='c')
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
#append data in horizontally and in vertically
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [30]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [31]:
#generate random number from NP
a1 = np.random.normal(5,0.5,10)
print(a1)


[5.24955131 4.89319778 4.58505967 5.25743004 4.67382865 4.57868471
 5.12421571 5.02566767 4.77146273 5.04367569]


In [32]:
#numpy.zeros() and numpy.one()
#generate an array with all zeroes - - numpy.zeros()
#numpy.zeros(shape,dtype=float,order='c')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [35]:
#np.ones(shape,dtype=float,order='c')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

In [38]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [39]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [40]:
#arange() - - particular
#numpy.arange(start,end,step)
#start - value
#end - value
#step - Gap between one value to another value

import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [43]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [45]:
#indexing and slicing of numpy
a1 = np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [46]:
a1 = np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]


In [50]:
a1 = np.array([(1,2,3),(4,5,6)])
print("first row",a1[0])

first row [1 2 3]


In [51]:
a1 = np.array([(1,2,3),(4,5,6)])
print("second row",a1[1])

second row [4 5 6]


In [55]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Slicing row",a1[1])

Slicing row [4 5 6]


In [57]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing column",a1[:,1])

slicing column [2 5]


In [58]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing last column",a1[:,2])

slicing last column [3 6]


In [59]:
a1 = np.array([(1,2,3),(4,5,6)])
print("row and column",a1[1,:1])

row and column [4]


In [60]:
#some math operation on given random numbers
#min - - returns least number
#max - - returns large number
#median - returns median value
#mean - - returns mean value
#GD - - gaussian distribution
a1 = np.random.normal(5,1,10)
print(a1)
print("Min value = ",np.min(a1))
print("Max value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("Median value = ",np.median(a1))

[5.92743089 4.23183439 6.60357195 5.49575943 3.70819796 7.44619925
 4.20971207 4.82531721 4.97936064 3.91829997]
Min value =  3.708197958036738
Max value =  7.446199245092686
Mean value =  5.13456837621526
Median value =  4.902338924231305


In [61]:
#multiply of 1d arrays
#numpy.dot(x,y)
c1 = np.array([1,2])
c2 = np.array([4,5])
np.dot(c1,c2)

14

In [62]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [63]:
b1 = np.array([(1,2),(3,6)])
b2 = np.array([(3,6),(1,2)])
np.dot(b1,b2)

array([[ 5, 10],
       [15, 30]])

**Pandas Basics**

Python is one of the popular programming language for data analysis

python is used for importing and analyzing pretty much faster and easier also 

Pandas dataFrames
            Data analysis with python

In [67]:
class test:
  def __init__(self,a):
    self.a =a
    
  def display(self):
    print(self.a)
obj = test()
obj.display()

TypeError: ignored

In [70]:
import pandas as pd
dict = {"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
       "EmailID":["anil1@gmail.com","akhil2@gmail.com","dinesh3@gmail.com","harsha4@gmail.com","ajay5@gmail.com","kranth6@gmail.com"],
        "MobileNumber":[999,888,777,888,999,777],
        "Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b = pd.DataFrame(dict)
b.index = ["01","02","03","04","05","06"]
print(b)

      Name            EmailID  MobileNumber Address
01    Anil    anil1@gmail.com           999     Hyd
02   Akhil   akhil2@gmail.com           888     Hyd
03  Dinesh  dinesh3@gmail.com           777     Hyd
04  Harsha  harsha4@gmail.com           888     Hyd
05    Ajay    ajay5@gmail.com           999     Hyd
06  Kranth  kranth6@gmail.com           777     Hyd


1. Lets input as string - - > Frequency of charform 0-9

    input : 213abc456def111
    
    output : 0 4 1 1 1 1 1 0 0 0
    
2. Check if the two strings are Anagrams

     abc  cba - ->  {a:1} {b:1} {c:1} - - true
     
     aabbcc ccbbaa - -false

In [71]:
import calendar
a=calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [74]:
#check whether two strings are Anagram 
def check(s1,s2): 
  if(sorted(s1)==sorted(s2)):
    return True
  else:
    return False

s1 = "abc" 
s2 = "cba"
check(s1,s2)

True

In [81]:
#frequency of character from 0-9
string = input("Enter a string")

Digits = ['0','1','2','3','4','5','6','7','8','9']
for i in range(0,10):
  print("Number is repeated times",i)
  print(string.count(Digits[i]))


Enter a string213abc456def111
Number is repeated times 0
0
Number is repeated times 1
4
Number is repeated times 2
1
Number is repeated times 3
1
Number is repeated times 4
1
Number is repeated times 5
1
Number is repeated times 6
1
Number is repeated times 7
0
Number is repeated times 8
0
Number is repeated times 9
0
